[package]
name = "gtp-rs"
version = "0.1.0"
authors = ["Misko Lee imiskolee@gmail.com"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/mod.rs"

[dependencies]
nom = "6.0.1"
wasm-bindgen = "0.2.69"
js-sys = "0.3.46"
wasm-bindgen-futures = "0.4.19"
